### ISSUE TITLE
关于GO逐行读取大文件的问题，Go为什么耗费时间是PHP7的8倍？

### ISSUE THREAD

**Issue by lixuancn** [duguying/blog#18]
最近写了个脚本，作为学习Go以来第一个实战。但是效果不理想。

一个文件。13G。逐行读取，将读取到的内容按空格切割为数组，取数组中Key＝8的值累加。最后得到这个累加的值。

很简单的文件处理程序。Go和PHP都是单线程顺序执行。

虽然PHP是最好的语言，但是Go作为编译型强类型语言，在我的认知里要比PHP快得多才对，就像C的速度是PHP5的1000倍。可现在Go为什么会出现这样的结果？

Go用了300秒，PHP5.6用了200秒，PHP7用了47秒。我是真的不敢相信这就是Google大力推广的Go。我宁愿相信这是我代码的问题

代码：http://www.oschina.net/question/938918_2145778

我周围没什么懂Go的人，问都不知道问谁了。国内社区基本很难获得理想的答案。请赐教！

**Comment by duguying** [comment]
你如果比较感兴趣的话可以自己研究一下go的源码 https://golang.org/src/bufio/bufio.go#L398

**Comment by lixuancn** [comment]
3q
